//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericInfo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenericInfoLog
    {
        public System.Guid Id { get; set; }
        public string IsRunning { get; set; }
        public string ServiceName { get; set; }
        public string ServiceTime { get; set; }
        public string ErrorInfo { get; set; }
    }
}
