//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuleObjects.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessRule
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DayFrom { get; set; }
        public string DayTill { get; set; }
        public string TimeFrom { get; set; }
        public string TimeTill { get; set; }
        public string Link { get; set; }
        public string Source { get; set; }
        public string Action { get; set; }
        public string Parameter { get; set; }
    }
}
