//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuleObjects.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trigger
    {
        public int Id { get; set; }
        public int RuleId { get; set; }
        public string Source { get; set; }
        public string Attribute { get; set; }
        public string Threshold { get; set; }
        public string Comparator { get; set; }
    }
}
